spring.application.name=urlshortner

spring.data.mongodb.uri=${MONGO_URI:mongodb://root:password@localhost:27017/urlshortner?authSource=admin}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

server.port=8091

app.base-url=${BASE_URL:http://localhost:8091}

app.jwt.secret=${JWT_SECRET:ewkjbfiwe237r62378hdbcyuwegr734@&!^%E^&!@TE^&@$^!@vdqvuqytf63&T&^T}
app.jwt.access-ttl-min=${JWT_ACCESS_TTL_MIN:15}
app.jwt.refresh-ttl-days=${JWT_REFRESH_TTL_DAYS:30}

# Enabling all endpoints
app.cors.origins="*"


app.rate.window-seconds=${RATE_WINDOW_SECONDS:60}
app.rate.max-hits=${RATE_MAX_HITS:120}
